name: vidora_player_v1
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # media_kit: ^1.2.0
  # media_kit_video: ^1.3.0
  # media_kit_libs_video: ^1.0.6
  # media_kit_libs_audio: ^1.0.6
  file_picker: ^10.2.0
  window_manager: ^0.5.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  subtitle_wrapper_package: ^2.2.1
  bitsdojo_window: ^0.1.6
  video_player: ^2.10.0
  video_player_win: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
      - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: false
  ios: false
  windows:
    icon_size: 48
    image_path: "assets/application_ic.png"
    generate: true